homepage/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.homepage, name='homepage'),
	url(r'^files/$', views.formfile, name='files'),
	url(r'^show/$', views.show, name='home1'),
	url(r'^show2/$', views.show_second, name='home2'),
	url(r'^show3/$', views.show_third, name='home3'),
	url(r'^show4/$', views.show_four, name='home4'),
	url(r'^show5/$', views.show_five, name='home5'),
	url(r'^show6/$', views.show_six, name='home6'),
	url(r'^show7/$', views.show_seven, name='home7'),
	url(r'^show8/$', views.show_eight, name='home8'),
	url(r'^show9/$', views.show_nine, name='home9'),
	url(r'^show10/$', views.show_ten, name='home10'),
	url(r'^show11/$', views.show_eleven, name='home11'),
	url(r'^show12/$', views.show_twelve, name='home12'),
	url(r'^show13/$', views.show_thirteen, name='home13'),
	url(r'^show14/$', views.show_fourteen, name='home14'),
	url(r'^show15/$', views.show_fifteen, name='home15'),
	url(r'^show16/$', views.show_sixteen, name='home16'),
	url(r'^project/$', views.project, name='project'),
	url(r'^contact/$', views.contactform, name='contact'),
	url(r'^profile/$', views.profile, name='profile'),
	# url(r'^comment_form/$', views.formss, name='commentform'),

]

projects/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls .static import static
from django.conf import settings
from accounts.views import (login_view,logout_view,register_view)
import homepage
from homepage import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/',include('homepage.urls',namespace="base")),
    url(r'^login/',login_view,name="login_view"),
    url(r'^logout/',logout_view,name="logout_view"),
    url(r'^register/',register_view,name="register_view")
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<head>
  <title>Circuits-Hub</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
     <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet'  type='text/css'>
      <script src="/static/javascript/external.js"></script>
     <link href='/static/css/style2.css' rel='stylesheet'  type='text/css'>


</head>
<body>

<nav class="navbar navbar-inverse sidebar" role="navigation">
    <div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" style="font-family:italic;font-size: x-large;"href="/home/">Circuits<span>Hub</span></a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="active"><a href="/home/">Home<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
				<li ><a href="/home/project/">Projects<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-th"></span></a></li>
				<li ><a href="{%url 'base:contact'%}">Messages<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-envelope"></span></a></li>
<!--
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-cog"></span></a>
					<ul class="dropdown-menu forAnimate" role="menu">
						<li><a href="#">Action</a></li>
						<li><a href="#">Another action</a></li>
						<li><a href="#">Something else here</a></li>
						<li class="divider"></li>
						<li><a href="#">Separated link</a></li>
						<li class="divider"></li>
						<li><a href="#">One more separated link</a></li>
					</ul>
				</li>
-->
				<li><a href="#">About us<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-info-sign"></span></a></li>
				<li ><a href="{% url 'base:profile' %}">Profile<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a></li>

<!--
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-cog"></span></a>
					<ul class="dropdown-menu forAnimate" role="menu">
						<li><a href="#">Action</a></li>
						<li><a href="#">Another action</a></li>
						<li><a href="#">Something else here</a></li>
						<li class="divider"></li>
						<li><a href="#">Separated link</a></li>
						<li class="divider"></li>
						<li><a href="#">One more separated link</a></li>
					</ul>
				</li>
-->
			</ul>
		</div>
	</div>
</nav>

{% block body %}

{% endblock %}
</body>

templates/base1.html
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
     <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet'  type='text/css'>

     <style>
.text-center {
  text-align: center;
}

.quote-card {
  background:#2F4F4F;
  color:whitesmoke;
  padding: 20px;
  padding-left: 50px;
  box-sizing: border-box;
  box-shadow: 0 2px 4px rgba(34, 34, 34, 0.12);
  position: relative;
  overflow: hidden;
  min-height: 120px;
}
.quote-card p {
  font-size: 22px;
  line-height: 1.5;
  margin: 0;
  max-width: 80%;
}

     </style>


</head>
<body>

<nav class="navbar navbar-inverse sidebar" role="navigation">
    <div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" style="font-family:italic"href="#"></a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="active"><a href="#">Home<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
				<li ><a href="#">Profile<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a></li>
				<li ><a href="#">Messages<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-envelope"></span></a></li>
<!--
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-cog"></span></a>
					<ul class="dropdown-menu forAnimate" role="menu">
						<li><a href="#">Action</a></li>
						<li><a href="#">Another action</a></li>
						<li><a href="#">Something else here</a></li>
						<li class="divider"></li>
						<li><a href="#">Separated link</a></li>
						<li class="divider"></li>
						<li><a href="#">One more separated link</a></li>
					</ul>
				</li>
-->
				<li><a href="#">Home<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
				<li ><a href="#">Profile<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a></li>
				<li ><a href="#">Messages<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-envelope"></span></a></li>
<!--
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-cog"></span></a>
					<ul class="dropdown-menu forAnimate" role="menu">
						<li><a href="#">Action</a></li>
						<li><a href="#">Another action</a></li>
						<li><a href="#">Something else here</a></li>
						<li class="divider"></li>
						<li><a href="#">Separated link</a></li>
						<li class="divider"></li>
						<li><a href="#">One more separated link</a></li>
					</ul>
				</li>
-->
			</ul>
		</div>
	</div>
</nav>

{% block bodys %}
{% endblock %}
</body>

templates/download1.html
{% extends 'show1.html' %}

{% block body1 %}
<div class="col-lg-2" xmlns="http://www.w3.org/1999/html">
    <a  href="{{ MEDIA_URL }}{{all.file.url}}" class="btn btn-primary btn-primary"><span class="glyphicon glyphicon-download-alt"></span> Download File</a>         </div>
{% endblock %}

{% block piyush %}

    <form method="post" action="{%url 'base:home2' %}">
    {% csrf_token %}

<div style="margin:50px">
<textarea style="height:150px;width:500px" class="form-control" name="content" rows="3" placeholder="Leave Your Comment"></textarea><br>

     &nbsp;&nbsp;&nbsp;&nbsp;<button class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-hand-up"></span> Comment</button>
   </div>
    </form>
    {% for x in comment %}
        <br>

        <div class="container">
	<div class="row">
	    <div class="container">
            <blockquote class="quote-card">
              <p>
                {{ x.content }}
              </p>

        </div>
	</div>
</div>


    {% endfor %}
{% endblock %}

templates/download10.html
{% extends 'show10.html' %}

{% block body_10%}
<div class="col-lg-2" xmlns="http://www.w3.org/1999/html">
    <a  href="{{ MEDIA_URL }}{{all.file.url}}" class="btn btn-primary btn-primary"><span class="glyphicon glyphicon-download-alt"></span> Download File</a>         </div>
{% endblock %}

{% block form_10 %}

    <form method="post" action="{%url 'base:home11' %}">
    {% csrf_token %}

<div style="margin:50px">
<textarea style="height:150px;width:500px" class="form-control" name="content" rows="3" placeholder="Leave Your Comment"></textarea><br>

     &nbsp;&nbsp;&nbsp;&nbsp;<button class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-hand-up"></span> Comment</button></div>
   </form>

    {% for x in comment %}
        <br>

        <div class="container">
	<div class="row">
	    <div class="container">
            <blockquote class="quote-card">
              <p>
                {{ x.content }}
              </p>

        </div>
	</div>
</div>


    {% endfor %}
{% endblock %}

templates/download12.html
{% extends 'show12.html' %}

{% block body_12%}
<div class="col-lg-2" xmlns="http://www.w3.org/1999/html">
    <a  href="{{ MEDIA_URL }}{{all.file.url}}" class="btn btn-primary btn-primary"><span class="glyphicon glyphicon-download-alt"></span> Download File</a>         </div>
{% endblock %}

{% block form_12%}

    <form method="post" action="{%url 'base:home13' %}">
    {% csrf_token %}

<div style="margin:50px">
<textarea style="height:150px;width:500px" class="form-control" name="content" rows="3" placeholder="Leave Your Comment"></textarea><br>

     &nbsp;&nbsp;&nbsp;&nbsp;<button class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-hand-up"></span> Comment</button></div>
   </form>

    {% for x in comment %}
        <br>

        <div class="container">
	<div class="row">
	    <div class="container">
            <blockquote class="quote-card">
              <p>
                {{ x.content }}
              </p>

        </div>
	</div>
</div>


    {% endfor %}
{% endblock %}

templates/download13.html
{% extends 'show13.html' %}

{% block body_13%}
<div class="col-lg-2" xmlns="http://www.w3.org/1999/html">
    <a  href="{{ MEDIA_URL }}{{all.file.url}}" class="btn btn-primary btn-primary"><span class="glyphicon glyphicon-download-alt"></span> Download File</a>         </div>
{% endblock %}

{% block form_13%}

    <form method="post" action="{%url 'base:home14' %}">
    {% csrf_token %}

<div style="margin:50px">
<textarea style="height:150px;width:500px" class="form-control" name="content" rows="3" placeholder="Leave Your Comment"></textarea><br>

     &nbsp;&nbsp;&nbsp;&nbsp;<button class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-hand-up"></span> Comment</button></div>
   </form>

    {% for x in comment %}
        <br>

        <div class="container">
	<div class="row">
	    <div class="container">
            <blockquote class="quote-card">
              <p>
                {{ x.content }}
              </p>

        </div>
	</div>
</div>


    {% endfor %}
{% endblock %}

templates/download3.html
{% extends 'show3.html' %}

{% block body_3 %}
<div class="col-lg-2" xmlns="http://www.w3.org/1999/html">
    <a  href="{{ MEDIA_URL }}{{all.file.url}}" class="btn btn-primary btn-primary"><span class="glyphicon glyphicon-download-alt"></span> Download File</a>         </div>
{% endblock %}

{% block form_3 %}

    <form method="post" action="{%url 'base:home4' %}">
    {% csrf_token %}

<div style="margin:50px">
<textarea style="height:150px;width:500px" class="form-control" name="content" rows="3" placeholder="Leave Your Comment"></textarea><br>

     &nbsp;&nbsp;&nbsp;&nbsp;<button class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-hand-up"></span> Comment</button></div>
   </form>

    {% for x in comment %}
        <br>

        <div class="container">
	<div class="row">
	    <div class="container">
            <blockquote class="quote-card">
              <p>
                {{ x.content }}
              </p>

        </div>
	</div>
</div>


    {% endfor %}
{% endblock %}

templates/download4.html
{% extends 'show4.html' %}

{% block body_4 %}
<div class="col-lg-2" xmlns="http://www.w3.org/1999/html">
    <a  href="{{ MEDIA_URL }}{{all.file.url}}" class="btn btn-primary btn-primary"><span class="glyphicon glyphicon-download-alt"></span> Download File</a>         </div>
{% endblock %}

{% block form_4 %}

    <form method="post" action="{%url 'base:home5' %}">
    {% csrf_token %}

<div style="margin:50px">
<textarea style="height:150px;width:500px" class="form-control" name="content" rows="3" placeholder="Leave Your Comment"></textarea><br>

     &nbsp;&nbsp;&nbsp;&nbsp;<button class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-hand-up"></span> Comment</button></div>
   </form>

    {% for x in comment %}
        <br>

        <div class="container">
	<div class="row">
	    <div class="container">
            <blockquote class="quote-card">
              <p>
                {{ x.content }}
              </p>

        </div>
	</div>
</div>


    {% endfor %}
{% endblock %}

templates/download7.html
{% extends 'show7.html' %}

{% block body_7%}
<div class="col-lg-2" xmlns="http://www.w3.org/1999/html">
    <a  href="{{ MEDIA_URL }}{{all.file.url}}" class="btn btn-primary btn-primary"><span class="glyphicon glyphicon-download-alt"></span> Download File</a>         </div>
{% endblock %}

{% block form_7 %}

    <form method="post" action="{%url 'base:home8' %}">
    {% csrf_token %}

<div style="margin:50px">
<textarea style="height:150px;width:500px" class="form-control" name="content" rows="3" placeholder="Leave Your Comment"></textarea><br>

     &nbsp;&nbsp;&nbsp;&nbsp;<button class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-hand-up"></span> Comment</button></div>
   </form>

    {% for x in comment %}
        <br>

        <div class="container">
	<div class="row">
	    <div class="container">
            <blockquote class="quote-card">
              <p>
                {{ x.content }}
              </p>

        </div>
	</div>
</div>


    {% endfor %}
{% endblock %}

templates/project.html

<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
     <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet'  type='text/css'>

     <style>

/* ==========================
Template name: Outlined Flat Buttons
Version: 1.0
Author: RowBootstrap
Author website: http://www.rowbootstrap.com/
========================== */


/* =================================
Basic Styling
================================= */
body,
html {
    width: 100%;
	height: 100%;
	margin: 0;
	padding: 0;
	font-family: 'Open Sans', sans-serif;
	color: #000000;
	background: #FFFFFF;
}

/* Text colors */

.text-color-white {
	color: #FFFFFF;
}

.text-color-black {
	color: #000000;
}

.text-color-theme {
	color: #6f5499;
}

/* Background colors */
.theme-bg{
	background: #6f5499;
}

.bg-black{
	background: #000000;
}

.secondary-bg {
	background: #f0ecf6;
}


/* Margin */

.margin-bottom-0 {
	margin-bottom: 0 !important;
}

.margin-bottom-10 {
	margin-bottom: 10px !important;
}

.margin-bottom-15 {
	margin-bottom: 15px !important;
}

.margin-bottom-20 {
	margin-bottom: 20px !important;
}

.margin-bottom-30 {
	margin-bottom: 30px !important;
}

.margin-bottom-40 {
	margin-bottom: 40px !important;
}

.margin-bottom-50 {
	margin-bottom: 50px !important;
}

.margin-bottom-60 {
	margin-bottom: 60px !important;
}

.margin-bottom-70 {
	margin-bottom: 70px !important;
}

.margin-bottom-80 {
	margin-bottom: 80px !important;
}

.margin-bottom-90 {
	margin-bottom: 90px !important;
}

.margin-bottom-100 {
	margin-bottom: 100px !important;
}

.margin-bottom-120 {
	margin-bottom: 120px !important;
}

.margin-right-0 {
	margin-right: 0 !important;
}

.margin-right-5 {
	margin-right: 5px !important;
}

.margin-right-10 {
	margin-right: 10px !important;
}

/* Padding surround */

.padding-0 {
	padding: 0px !important;
}

.padding-30 {
	padding: 30px !important;
}

.padding-50 {
	padding: 40px !important;
}


/* Buttons */

.btn {
	letter-spacing: 1px;
	text-decoration: none;
	background: none;
    -moz-user-select: none;
    background-image: none;
    border: 1px solid transparent;
    border-radius: 0;
    cursor: pointer;
    display: inline-block;
    margin-bottom: 0;
    vertical-align: middle;
    white-space: nowrap;
	font-size:14px;
	line-height:20px;
	font-weight:700;
	text-transform:uppercase;
	border: 1px solid;
	padding:8px 20px;
}

.btn-outlined {
    border-radius: 0;
    -webkit-transition: all 0.3s;
       -moz-transition: all 0.3s;
            transition: all 0.3s;
}

.btn-outlined.btn-theme {
    background: none;
    color: #6f5499;
	border-color: #6f5499;
}

.btn-outlined.btn-theme:hover,
.btn-outlined.btn-theme:active {
    color: #FFF;
    background: #6f5499;
    border-color: #6f5499;
}

.btn-outlined.btn-black {
    background: none;
    color: #000000;
	border-color: #000000;
}

.btn-outlined.btn-black:hover,
.btn-outlined.btn-black:active {
    color: #FFF;
    background: #000000;
    border-color: #000000;
}

.btn-outlined.btn-white {
    background: none;
    color: #FFFFFF;
	border-color: #FFFFFF;
}

.btn-outlined.btn-white:hover,
.btn-outlined.btn-white:active {
    color: #6f5499;
    background: #FFFFFF;
    border-color: #FFFFFF;
}

         /* BUTTONS*/
.buttons {
    display: flex;
}

.button {
    box-sizing: border-box;
    color: #000000;
    display: block;
    font-size: 3em;
    margin: 0 1em 0.3em 0;
    padding: 0.5em 1em;
    text-align: center;
    flex: 1;
    border: thin solid;
}

.button:hover{
    color: #FFF;
    background: #000000;
    border-color: #000000;
    text-decoration: none;
}





    </style>

</head>
<body>


<div class="container">


       <div class="buttons row1">



            <a href="#" class="button button-02">
         SOME OF OUR AMAZING PROJECTS
            </a>




</div>
</div>
<div class="container-fluid padding-50">
	<div class="row">

    	<div class="col-lg-12">
        	<div class="container">
            	<div class="row">
                	<div class="col-lg-6 col-lg-offset-3">

                        <p>
                            <a href="#" class="btn btn-outlined btn-theme" data-wow-delay="0.7s">Square Wave Generator</a>
                        </p>
                         <p>
                            <a href="#" class="btn btn-outlined btn-theme" data-wow-delay="0.7s">Temparature Control LED</a>
                        </p>
                         <p>
                            <a href="#" class="btn btn-outlined btn-theme" data-wow-delay="0.7s">LED Blinking (using 555 IC)</a>
                        </p>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid secondary-bg padding-50">
	<div class="row">
    	<div class="col-lg-12">
        	<div class="container">
            	<div class="row">
                	<div class="col-lg-6 col-lg-offset-3">

                        <p>
                            <a href="#" class="btn btn-outlined btn-black" data-wow-delay="0.7s">Voltage Rectifier(using 7805 IC)</a>
                        </p>
                        <p>
                            <a href="#" class="btn btn-outlined btn-black" data-wow-delay="0.7s">Water Level Indicator</a>
                        </p>
                        <p>
                            <a href="#" class="btn btn-outlined btn-black" data-wow-delay="0.7s">Disco Light</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid theme-bg padding-50">
	<div class="row">
    	<div class="col-lg-12">
        	<div class="container">
            	<div class="row">
                	<div class="col-lg-6 col-lg-offset-3">

                        <p>
                            <a href="#" class="btn btn-outlined btn-white" data-wow-delay="0.7s">Voltage Tripper</a>
                        </p>
                            <a href="#" class="btn btn-outlined btn-white" data-wow-delay="0.7s">Electronics Dice Game</a>
                        </p>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</body>

templates/show1.html
{% extends 'base1.html' %}
{% block bodys %}
{#<head>#}
{#<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">#}
{#  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>#}
{#  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>#}
{##}
{#    <title>Electronic dice for game</title>#}
{##}
{#</head>#}

<div style="background-color: #CCCCCC">
    <div class="container">

                <div class="row">
            <div class="col-lg-8">

                <!-- Blog Post -->

                <!-- Title -->
                <h1>Electronic dice for game|<small> 100% Tested</small></h1><br>

                </div>
                    <br>
{% block body1 %}
{% endblock %}


            </div>
                    <br>

                             <div class=" col-lg-offset-2 col-lg-8">
                        <img class="img-responsive" width="100%" src="/static/images/touch.png" alt="">
                         </div>




    <br>
       <br>
    <div class="row">
    <div class="container col-lg-offset-2 col-lg-8 align:center">
  <h2>Componenet Required:-</h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Sr No.</th>
        <th>Componenet</th>
        <th>Quantity</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1.</td>
        <td>IC CD4017</td>
        <td>1</td>
      </tr>
      <tr>
        <td>2.</td>
        <td>LED</td>
        <td>6</td>
      </tr>
        <tr>
        <td>3.</td>
        <td>Touch Plate </td>
        <td>1</td>
      </tr>

        <tr>
        <td>4.</td>
        <td>Supply(5V)</td>
        <td>1</td>
      </tr>

    </tbody>
  </table>
</div>
    </div>


  <div class="container">
      <div class="jumbotron" style="background-color:#3b5998">
<h2 style="color:white">Description:-</h2>

<h4 style="color:white">

When we touch the plate attached to pin number  14 of CD4017, it receive the  pulse  which is like fast triggering.<br>
      LED attached to the output pin of CD4017 start glowing rapidly in sequence.<br>
When we remove the finger from touch plate, it is totally unpredictable which led will remain ON.<br>
This unpredictability makes this project useful in generating random no. which can be used in games.<br>
      </h4>

        </div>

                    </div>
</div>
{% block piyush %}
{% endblock %}
{% endblock bodys %}